name: geolocation_ip
description: A Dart package leverages the IP-API.com service to provide geolocation data based on IP addresses.
version: 0.0.3
repository: https://github.com/elrizwiraswara/geolocation_ip

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  http: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

platforms:
  android:
  ios:
  macos:
  web:
  windows:

topics:
  - ip-geolocation
  - geolocation
  - ip-api
  - location